# Generated by Django 2.2 on 2019-07-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstoccurrence', models.DateTimeField()),
                ('node', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('alarm', models.TextField()),
            ],
        ),
    ]
